/* © 2026 Mario Dal Zuffo - V° Centro di Mobilitazione Veneto (CRI Corpo Militare). Tutti i diritti riservati. Vietati copia, modifica, distribuzione e uso senza autorizzazione scritta dell'autore. */
const ORG={attesa:null,ricerca:null,dopoLogin:null};function leggiSessione(){try{const e=JSON.parse(localStorage.getItem("dsaSessioneOrganizzatore")||"null");if(e&&e.sess&&e.scadenza&&e.scadenza>new Date().toISOString().slice(0,16).replace("T"," "))return e}catch{}return null}function salvaSessione(e){try{e?localStorage.setItem("dsaSessioneOrganizzatore",JSON.stringify(e)):localStorage.removeItem("dsaSessioneOrganizzatore")}catch{}aggiornaPulsanteOrganizzatore()}function aggiornaPulsanteOrganizzatore(){const e=document.getElementById("btnAreaOrganizzatore");if(!e)return;const a=leggiSessione();e.textContent=a?`\u{1F464} Le mie attivit\xE0 (${a.persona.cognome})`:"\u{1F464} Area organizzatore"}function apriAreaOrganizzatore(){apriOverlay("ovOrganizzatore"),leggiSessione()?caricaDashboard():mostraLogin()}function chiudiAreaOrganizzatore(){ORG.dopoLogin=null,ORG.attesa&&(clearInterval(ORG.attesa),ORG.attesa=null),chiudiOverlay("ovOrganizzatore")}function mostraLogin(){const e=document.getElementById("orgContenuto");e.innerHTML=`
        <div class="banner-attivita">
            <p>${ORG.dopoLogin?"<b>Per creare un'attivit\xE0 devi prima accedere.</b> ":""}Qui trovi tutte le attivit\xE0 che hai organizzato. Non serve una password: scegli il tuo nome e ti arriver\xE0 una
               <b>mail di conferma</b> all'indirizzo registrato. Clicca <b>CONFERMA</b> nella mail e questa pagina si aprir\xE0 da sola.</p>
        </div>
        <div class="form-group"><label>Il tuo nome</label><div id="orgRicerca"></div><div id="orgScelto"></div></div>
        <button class="btn btn-attivita" id="orgInvia" disabled>\u2709\uFE0F Invia la mail di accesso</button>`;let a=null;const n=()=>{document.getElementById("orgRicerca").classList.toggle("hidden",!!a),document.getElementById("orgScelto").innerHTML=a?`<div class="persona-scelta"><span>\u{1F464} ${escHtml(a.label)}</span><button type="button" class="btn-sm grigio" id="orgCambia">Cambia</button></div>`:"",document.getElementById("orgInvia").disabled=!a,a&&(document.getElementById("orgCambia").onclick=()=>{a=null,n()})};ORG.ricerca=creaRicercaPersona(document.getElementById("orgRicerca"),{placeholder:"Scrivi il tuo cognome...",onScelta:o=>{a=o,n()}}),document.getElementById("orgInvia").onclick=()=>richiediAccesso(a),setTimeout(()=>ORG.ricerca.input.focus(),50)}async function richiediAccesso(e){attesa("Invio della mail di accesso...");let a;try{a=await api("loginRichiesta",{organizzatoreId:e.id})}catch(i){erroreSwal(i);return}Swal.close();const n=document.getElementById("orgContenuto");n.innerHTML=`
        <div class="banner-attivita" style="text-align:center;">
            <h3>\u{1F4E7} Controlla la tua email</h3>
            <p>Abbiamo inviato una mail a <b>${escHtml(a.email)}</b>.</p>
            <p>Apri la mail e clicca <b>CONFERMA</b>: questa pagina si aggiorner\xE0 da sola.<br>
               Il link scade tra ${a.minuti} minuti. Se non la trovi controlla lo spam.</p>
            <p class="muted" id="orgAttesaStato">In attesa di conferma...</p>
        </div>
        <p style="text-align:center;"><button class="btn-sm grigio" id="orgAnnulla">Annulla</button></p>`,document.getElementById("orgAnnulla").onclick=()=>{clearInterval(ORG.attesa),ORG.attesa=null,mostraLogin()};const o=Date.now();let t=!1;ORG.attesa=setInterval(async()=>{if(!t){t=!0;try{const i=await api("loginStato",{sid:a.sid,poll:a.poll});if(i.stato==="confermata"){if(clearInterval(ORG.attesa),ORG.attesa=null,salvaSessione({sess:i.sess,scadenza:i.scadenza,persona:i.persona}),Swal.fire({toast:!0,position:"top",timer:2500,showConfirmButton:!1,icon:"success",title:"Accesso confermato"}),caricaDashboard(),ORG.dopoLogin){const s=ORG.dopoLogin;ORG.dopoLogin=null,s()}}else if(i.stato==="rifiutata"||i.stato==="scaduta")clearInterval(ORG.attesa),ORG.attesa=null,n.innerHTML=`<div class="banner-attivita banner-err"><h3>${i.stato==="rifiutata"?"Accesso rifiutato":"Richiesta scaduta"}</h3>
                    <p>${i.stato==="rifiutata"?"L'accesso \xE8 stato rifiutato dalla mail.":"Il tempo per confermare \xE8 finito."}</p></div>
                    <button class="btn" id="orgRiprova">Riprova</button>`,document.getElementById("orgRiprova").onclick=mostraLogin;else{const s=document.getElementById("orgAttesaStato");s&&(s.textContent=`In attesa di conferma... (${Math.round((Date.now()-o)/1e3)} s)`)}}catch{const s=document.getElementById("orgAttesaStato");s&&(s.textContent="Connessione instabile, riprovo...")}finally{t=!1}}},3e3)}async function caricaDashboard(){const e=leggiSessione();if(!e){mostraLogin();return}const a=document.getElementById("orgContenuto");a.innerHTML="<p>Caricamento delle tue attivit\xE0...</p>";let n;try{n=await api("mieAttivita",{sess:e.sess})}catch(t){if(/scadut|richiesto/i.test(t.message)){salvaSessione(null),mostraLogin();return}a.innerHTML=`<div class="banner-attivita banner-err"><p>${escHtml(t.message)}</p></div><button class="btn-sm grigio" onclick="caricaDashboard()">\u{1F504} Riprova</button>`;return}const o=t=>t.stato==="inviata"?'<span class="badge inviata">\u{1F4E8} Inviata</span>':t.stato==="parziale"?`<span class="badge attesa">\u{1F4E8} Inviate ${t.inviate}/${t.totale}</span>`:t.totale&&t.caricate===t.totale?'<span class="badge ok">\u2705 Pronta da inviare</span>':'<span class="badge attesa">\u23F3 In raccolta</span>';a.innerHTML=`
        <div class="info-riga" style="justify-content:space-between; align-items:center;">
            <span>\u{1F464} <b>${escHtml(n.persona.label)}</b> <span class="muted">\xB7 accesso valido fino al ${dataOraIT(e.scadenza)}</span></span>
            <span style="display:flex; gap:6px;">
                <button class="btn-sm verde" id="orgNuova">\u2795 Nuova attivit\xE0</button>
                <button class="btn-sm grigio" id="orgAggiorna">\u{1F504}</button>
                <button class="btn-sm grigio" id="orgEsci">Esci</button>
            </span>
        </div>
        ${n.attivita.length?`
        <table class="tabella">
            <thead><tr><th>Attivit\xE0</th><th>Periodo</th><th>DSA</th><th>Stato</th></tr></thead>
            <tbody>${n.attivita.map(t=>`
                <tr class="cliccabile" data-id="${escHtml(t.id)}">
                    <td><b>${escHtml(t.nome)}</b><br><span class="muted">${escHtml(etichettaTipo(t.tipoServizio))}</span></td>
                    <td>${dataIT(t.dataDal)} - ${dataIT(t.dataAl)}</td>
                    <td><b>${t.caricate}/${t.totale}</b><div class="progress"><div style="width:${t.totale?Math.round(t.caricate/t.totale*100):0}%"></div></div></td>
                    <td>${o(t)}</td>
                </tr>`).join("")}
            </tbody>
        </table>
        <p class="nota">Clicca un'attivit\xE0 per gestirla.</p>`:'<p class="nota">Non hai ancora organizzato attivit\xE0. Crea la prima con "\u2795 Nuova attivit\xE0".</p>'}`,document.getElementById("orgNuova").onclick=()=>apriNuovaAttivita(!1),document.getElementById("orgAggiorna").onclick=caricaDashboard,document.getElementById("orgEsci").onclick=esciOrganizzatore,a.querySelectorAll("tr[data-id]").forEach(t=>t.onclick=()=>{caricaGestione({att:t.dataset.id,auth:()=>({sess:(leggiSessione()||{}).sess}),contenitore:a,admin:!1,onIndietro:caricaDashboard})})}async function esciOrganizzatore(){const e=leggiSessione();if(salvaSessione(null),e)try{await api("logout",{sess:e.sess})}catch{}mostraLogin()}async function initConfermaAccesso(e,a,n){window.MODALITA={tipo:"accesso"},document.getElementById("vistaDSA").classList.add("hidden"),document.getElementById("titoloPagina").textContent="ACCESSO AREA ORGANIZZATORE";const o=document.getElementById("vistaGestione");o.classList.remove("hidden"),o.innerHTML="<p>Caricamento...</p>";let t;try{t=await api("getAccesso",{sid:e,t:a})}catch(c){o.innerHTML=`<div class="banner-attivita banner-err"><h3>Link non valido</h3><p>${escHtml(c.message)}</p></div>`;return}if(t.stato!=="attesa"){const c={confermata:"Accesso gi\xE0 confermato.",rifiutata:"Accesso gi\xE0 rifiutato.",scaduta:"Richiesta scaduta: ripeti l'accesso dal portale.",chiusa:"Accesso gi\xE0 chiuso."};o.innerHTML=`<div class="banner-attivita banner-warn"><h3>${escHtml(c[t.stato]||t.stato)}</h3></div>`;return}const i=n==="conferma";o.innerHTML=`
        <div class="banner-attivita ${i?"":"banner-err"}">
            <h3>Richiesta di accesso</h3>
            <p>Il ${dataOraIT(t.richiestoIl)} qualcuno ha chiesto di accedere all'area organizzatore del portale DSA come <b>${escHtml(t.persona)}</b>.</p>
            <p>${i?"Se sei stato tu, conferma.":"Se non sei stato tu, rifiuta: l'accesso verr\xE0 bloccato."}</p>
        </div>
        ${i?`<button class="btn btn-attivita" id="accPrincipale">\u2705 CONFERMA, sono io</button>
               <p style="text-align:center;"><button class="btn-sm rosso" id="accAltro">\u2716 Non sono stato io, rifiuta</button></p>`:`<button class="btn" style="background:#d32f2f;" id="accPrincipale">\u2716 RIFIUTA l'accesso</button>
               <p style="text-align:center;"><button class="btn-sm verde" id="accAltro">\u2705 Sono io, conferma</button></p>`}`;const s=async c=>{attesa("Un momento...");try{await api("confermaAccesso",{sid:e,t:a,azione:c}),Swal.close(),o.innerHTML=c==="conferma"?`<div class="banner-attivita"><h3>\u2705 Accesso confermato</h3><p>Torna sulla pagina da cui hai chiesto l'accesso: si \xE8 gi\xE0 aperta l'area organizzatore. Puoi chiudere questa finestra.</p></div>`:`<div class="banner-attivita banner-err"><h3>Accesso rifiutato</h3><p>Nessuno \xE8 entrato con il tuo nome. Se ricevi altre richieste che non hai fatto, avvisa l'Ufficio Operazioni.</p></div>`}catch(r){erroreSwal(r)}};document.getElementById("accPrincipale").onclick=()=>s(i?"conferma":"rifiuta"),document.getElementById("accAltro").onclick=()=>s(i?"rifiuta":"conferma")}
